# Generated by Django 2.1 on 2020-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='kent'),
            preserve_default=False,
        ),
    ]
