# Generated by Django 2.1 on 2020-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_business_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='post.jpg', upload_to='photos/'),
        ),
    ]
