# Generated by Django 2.1 on 2020-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20200226_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(default='biz.jpg', upload_to='photos/'),
        ),
    ]
